# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
